### ISSUE TITLE
Double creating plugin resources when you hit the 'save/create' button twice

### ISSUE THREAD

**Issue by jableader** [twitchyliquid64/CNC#8]
Add a resource to a plugin, give it its stats and then hit create, hit ok then hit create again and you now have two resources. 

My suggestion is to actually create the resource on the DB when you hit 'new resource' on the plugin edit page, then just go into edit that and scrap any of this create based stuff. Thoughts?

**Comment by twitchyliquid64** [comment]
Agreed
